LawOffice/LawOffice/Controllers/CaseLegalProceduresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using LawOffice.Models;

namespace LawOffice.Controllers
{
	[Authorize]
	public class CaseLegalProceduresController : Controller
	{
		private LawOfficeDBContext db = new LawOfficeDBContext();

		// GET: CaseLegalProcedures
		public ActionResult Index ()
		{
			if (User.IsInRole("Administrator") || User.IsInRole("Client"))
			{
				var casesLegalProcedure = db.CasesLegalProcedures.Include(c => c.Case).Include(c => c.LegalProcedure);
				return View(casesLegalProcedure.ToList());
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: CaseLegalProcedures/Details/5
		//public ActionResult Details (int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	CaseLegalProcedure caseLegalProcedure = db.CasesLegalProcedure.Find(id);
		//	if (caseLegalProcedure == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	return View(caseLegalProcedure);
		//}

		// GET: CaseLegalProcedures/Create
		public ActionResult Create (int id)
		{
			if (User.IsInRole("Administrator") || User.IsInRole("Lawyer"))
			{
				ViewBag.CaseId = new SelectList(db.Cases, "Id", "Number");
				ViewBag.LegalProcedureId = new SelectList(db.LegalProcedures, "Id", "Name");
				ViewData["CaseId"] = id;
				return View();
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// POST: CaseLegalProcedures/Create
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create ([Bind(Include = "Id,CaseId,LegalProcedureId,Date,Result")] CaseLegalProcedure caseLegalProcedure)
		{
			if (User.IsInRole("Administrator") || User.IsInRole("Lawyer"))
			{
				if (ModelState.IsValid)
				{
					db.CasesLegalProcedures.Add(caseLegalProcedure);
					db.SaveChanges();
					return RedirectToAction("Details", "Cases", new { id = caseLegalProcedure.CaseId });
				}

				ViewBag.CaseId = new SelectList(db.Cases, "Id", "Number", caseLegalProcedure.CaseId);
				ViewBag.LegalProcedureId = new SelectList(db.LegalProcedures, "Id", "Name", caseLegalProcedure.LegalProcedureId);
				return View(caseLegalProcedure);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: CaseLegalProcedures/Edit/5
		//public ActionResult Edit (int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	CaseLegalProcedure caseLegalProcedure = db.CasesLegalProcedure.Find(id);
		//	if (caseLegalProcedure == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	ViewBag.CaseId = new SelectList(db.Cases, "Id", "Number", caseLegalProcedure.CaseId);
		//	ViewBag.LegalProcedureId = new SelectList(db.LegalProcedures, "Id", "Name", caseLegalProcedure.LegalProcedureId);
		//	return View(caseLegalProcedure);
		//}

		// POST: CaseLegalProcedures/Edit/5
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public ActionResult Edit ([Bind(Include = "Id,CaseId,LegalProcedureId,Date,Result")] CaseLegalProcedure caseLegalProcedure)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		db.Entry(caseLegalProcedure).State = EntityState.Modified;
		//		db.SaveChanges();
		//		return RedirectToAction("Index");
		//	}
		//	ViewBag.CaseId = new SelectList(db.Cases, "Id", "Number", caseLegalProcedure.CaseId);
		//	ViewBag.LegalProcedureId = new SelectList(db.LegalProcedures, "Id", "Name", caseLegalProcedure.LegalProcedureId);
		//	return View(caseLegalProcedure);
		//}

		// GET: CaseLegalProcedures/Delete/5
		//public ActionResult Delete (int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	CaseLegalProcedure caseLegalProcedure = db.CasesLegalProcedure.Find(id);
		//	if (caseLegalProcedure == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	return View(caseLegalProcedure);
		//}

		// POST: CaseLegalProcedures/Delete/5
		//[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		//public ActionResult DeleteConfirmed (int id)
		//{
		//	CaseLegalProcedure caseLegalProcedure = db.CasesLegalProcedure.Find(id);
		//	db.CasesLegalProcedure.Remove(caseLegalProcedure);
		//	db.SaveChanges();
		//	return RedirectToAction("Index");
		//}

		protected override void Dispose (bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

LawOffice/LawOffice/Controllers/LawyersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using LawOffice.Models;
using LawOffice.Models.Security;
using LawOffice.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using OfficeOpenXml;

namespace LawOffice.Controllers
{
	[Authorize]
	public class LawyersController : Controller
	{
		private LawOfficeDBContext db = new LawOfficeDBContext();

		// GET: Lawyers
		public ActionResult Index ()
		{
			if (User.IsInRole("Administrator"))
			{
				var lawyers = db.Lawyers.Include(l => l.LawyerStatus);
				return View(lawyers.ToList());
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		public ActionResult LoadFromAPI ()
		{
			HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://localhost:44334/api/Lawyers");
			request.Accept = "application/xml";
			WebResponse response = request.GetResponse();
			XmlDocument doc = new XmlDocument();
			doc.Load(response.GetResponseStream());
			XmlElement root = doc.DocumentElement;
			foreach (XmlElement lawyerNode in root)
			{
				int id = Convert.ToInt32(lawyerNode["Id"].InnerText);
				Lawyer lawyer = db.Lawyers.Find(id);
				if (lawyer == null)
				{
					Lawyer newLawyer = new Lawyer()
					{
						Surname = lawyerNode["Surname"].InnerText,
						Name = lawyerNode["Name"].InnerText,
						Patronymic = lawyerNode["Patronymic"].InnerText,
						StartDate = DateTime.Parse(lawyerNode["StartDate"].InnerText),
						LawyerStatusId = int.Parse(lawyerNode["LawyerStatusId"].InnerText),
						Email = lawyerNode["Email"].InnerText,
					};
					db.Lawyers.Add(newLawyer);
				}
				else
				{
					lawyer.Surname = lawyerNode["Surname"].InnerText;
					lawyer.Name = lawyerNode["Name"].InnerText;
					lawyer.Patronymic = lawyerNode["Patronymic"].InnerText;
					lawyer.StartDate = DateTime.Parse(lawyerNode["StartDate"].InnerText);
					lawyer.LawyerStatusId = int.Parse(lawyerNode["LawyerStatusId"].InnerText);
				}
			}
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		// GET: Lawyers/Details/5
		public ActionResult Details (int? id)
		{
			if (User.IsInRole("Lawyer"))
			{
				LawOfficeIdentityDBContext dbIdentity = new LawOfficeIdentityDBContext();
				UserStore<User> userStore = new UserStore<User>(dbIdentity);
				UserManager<User> userManager = new UserManager<User>(userStore);
				RoleStore<Role> roleStore = new RoleStore<Role>(dbIdentity);
				RoleManager<Role> roleManager = new RoleManager<Role>(roleStore);
				User user = userManager.FindByName(HttpContext.User.Identity.Name);
				try
				{
					id = db.Lawyers.Where(l => l.Email == user.Email).FirstOrDefault().Id;
				}
				catch { }
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				LawyerDetails lawyerDetails = new LawyerDetails();
				lawyerDetails.Lawyer = db.Lawyers.Include(l => l.Cases).Where(l => l.Id == id).FirstOrDefault();
				lawyerDetails.Cases = db.Cases.Include(c => c.CaseResult).Include(c => c.CaseStatus).Where(c => c.Lawyers.Contains(db.Lawyers.Where(l => l.Id == id).FirstOrDefault())).ToList();
				if (lawyerDetails.Lawyer == null)
				{
					return HttpNotFound();
				}
				return View(lawyerDetails);
			}
			else
			{
				if (User.IsInRole("Administrator"))
				{
					if (id == null)
					{
						return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
					}
					LawyerDetails lawyerDetails = new LawyerDetails();
					lawyerDetails.Lawyer = db.Lawyers.Include(l => l.Cases).Where(l => l.Id == id).FirstOrDefault();
					lawyerDetails.Cases = db.Cases.Include(c => c.CaseResult).Include(c => c.CaseStatus).Where(c => c.Lawyers.Contains(db.Lawyers.Where(l => l.Id == id).FirstOrDefault())).ToList();
					if (lawyerDetails.Lawyer == null)
					{
						return HttpNotFound();
					}
					return View(lawyerDetails);
				}
				else
				{
					return new HttpStatusCodeResult(403);
				}
			}
		}

		// GET: Lawyers/Create
		public ActionResult Create ()
		{
			if (User.IsInRole("Administrator"))
			{
				ViewBag.LawyerStatusId = new SelectList(db.LawyerStatuses, "Id", "Name");
				Lawyer lawyer = new Lawyer();
				lawyer.StartDate = DateTime.Now;
				return View(lawyer);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// POST: Lawyers/Create
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create ([Bind(Include = "Id,Surname,Name,Patronymic,StartDate,Photo,LawyerStatusId")] Lawyer lawyer)
		{
			if (User.IsInRole("Administrator"))
			{
				lawyer.StartDate = DateTime.Now;
				lawyer.LawyerStatusId = 1;
				if (ModelState.IsValid)
				{
					db.Lawyers.Add(lawyer);
					db.SaveChanges();
					return RedirectToAction("Index");
				}

				ViewBag.LawyerStatusId = new SelectList(db.LawyerStatuses, "Id", "Name", lawyer.LawyerStatusId);
				return View(lawyer);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: Lawyers/Edit/5
		public ActionResult Edit (int? id)
		{
			if (User.IsInRole("Administrator"))
			{
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				Lawyer lawyer = db.Lawyers.Find(id);
				if (lawyer == null)
				{
					return HttpNotFound();
				}
				ViewBag.LawyerStatusId = new SelectList(db.LawyerStatuses, "Id", "Name", lawyer.LawyerStatusId);
				return View(lawyer);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// POST: Lawyers/Edit/5
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit ([Bind(Include = "Id,Surname,Name,Patronymic,StartDate,Photo,LawyerStatusId")] Lawyer lawyer)
		{
			if (User.IsInRole("Administrator"))
			{
				if (ModelState.IsValid)
				{
					db.Entry(lawyer).State = EntityState.Modified;
					db.SaveChanges();
					return RedirectToAction("Index");
				}
				ViewBag.LawyerStatusId = new SelectList(db.LawyerStatuses, "Id", "Name", lawyer.LawyerStatusId);
				return View(lawyer);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		public ActionResult Add (int id)
		{
			if (User.IsInRole("Administrator"))
			{
				var lawyers = db.Lawyers.Include(l => l.LawyerStatus).Include(l => l.Cases).ToList();
				for (int i = 0; i < lawyers.Count; i++)
				{
					foreach (var @case in lawyers[i].Cases)
					{
						if (@case.Id == id)
						{
							lawyers.RemoveAt(i);
						}
					}
				}
				ViewData["CaseId"] = id;
				ViewBag.LawyerId = new SelectList(lawyers, "Id", "FIO");
				return View();
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Add (int LawyerId, int CaseId)
		{
			if (User.IsInRole("Administrator"))
			{
				if (ModelState.IsValid)
				{
					var lawyer = db.Lawyers.Include(l => l.Cases).Where(l => l.Id == LawyerId).First();
					lawyer.Cases.Add(db.Cases.Where(c => c.Id == CaseId).First());
					db.SaveChanges();
					return RedirectToAction("Details", "Cases", new { id = CaseId });
				}
				var lawyers = db.Lawyers.Include(l => l.LawyerStatus).Include(l => l.Cases).ToList();
				for (int i = 0; i < lawyers.Count; i++)
				{
					foreach (var @case in lawyers[i].Cases)
					{
						if (@case.Id == (int)ViewData["CaseId"])
						{
							lawyers.RemoveAt(i);
						}
					}
				}
				ViewBag.LawyerId = new SelectList(lawyers, "Id", "Surname");
				return View();
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: Lawyers/Delete/5
		//public ActionResult Delete (int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	Lawyer lawyer = db.Lawyers.Find(id);
		//	if (lawyer == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	return View(lawyer);
		//}

		// POST: Lawyers/Delete/5
		//[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		//public ActionResult DeleteConfirmed (int id)
		//{
		//	Lawyer lawyer = db.Lawyers.Find(id);
		//	db.Lawyers.Remove(lawyer);
		//	db.SaveChanges();
		//	return RedirectToAction("Index");
		//}

		[Authorize(Roles = "Administrator")]
		public FileResult GetLawyersStatistics (int id)
		{
			if (id == 1)
			{
				ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
				string originalFilePath = Server.MapPath("~/Content/Reports/lawyer_statistics.xlsx");
				FileInfo originalFileInfo = new FileInfo(originalFilePath);
				string resultFilePath = Server.MapPath("~/Content/Reports/report.xlsx");
				FileInfo resultFileInfo = new FileInfo(resultFilePath);
				using (ExcelPackage excelPackage = new ExcelPackage(originalFileInfo))
				{
					excelPackage.Workbook.Properties.Author = "Mark Chuvanov";
					excelPackage.Workbook.Properties.Title = "Статистика по адвокатам";
					excelPackage.Workbook.Properties.Subject = "Результаты деятельности адвокатов";
					excelPackage.Workbook.Properties.Created = DateTime.Now;
					ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets["Statistics"];
					int startLine = 3;
					var lawyers = db.Lawyers.Include(l => l.Cases).ToList();
					foreach (var lawyer in lawyers)
					{
						worksheet.Cells[startLine, 1].Value = lawyer.Surname;
						worksheet.Cells[startLine, 2].Value = lawyer.Name;
						worksheet.Cells[startLine, 3].Value = lawyer.Patronymic;
						worksheet.Cells[startLine, 4].Value = lawyer.Cases.Count;
						double number = 0;
						foreach (var @case in lawyer.Cases)
						{

LawOffice/LawOffice/Views/Cases/Create.cshtml
@model LawOffice.Models.Case

@{
    ViewBag.Title = "Create";
}

<h2>Добавить новое дело</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal h4">
        <hr />
        @Html.Hidden("ClientId", ViewData["Id"])
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Адвокат</label>
            <div class="col-md-10">
                @Html.DropDownList("LawyerId", ViewBag.LawyerId as SelectList, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить дело" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LawOffice/LawOffice/Views/Cases/Details.cshtml
@model LawOffice.ViewModels.CaseDetails

@{
    ViewBag.Title = "Details";
}

<h2>Подробная информация о деле</h2>

<div>
    <hr />
    <dl class="dl-horizontal h4">
        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case.Number)
        </dd>

        <dt style="width:200px;margin-right:10px">
            <label style="margin:0">ФИО клиента</label>
        </dt>

        <dd>
            <p style="margin:0">@Model.Case.Client.Surname @Model.Case.Client.Name @Model.Case.Client.Patronymic</p>
        </dd>

        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.CaseStatus.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case.CaseStatus.Name)
        </dd>

        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.CaseResult.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case.CaseResult.Name)
        </dd>

        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.OpeningDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Case.OpeningDate)
        </dd>

        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.ClosingDate)
        </dt>

        <dd>
            @if (Model.Case.CaseStatusId == 2)
            {
                @Html.DisplayFor(model => model.Case.ClosingDate)
            }
        </dd>

        <dt style="width:200px;margin-right:10px">
            @Html.DisplayNameFor(model => model.Case.Costs)
        </dt>

        <dd>
            @if (Model.Case.Costs > 0)
            {
                @Html.DisplayFor(model => model.Case.Costs)
            }
        </dd>

    </dl>
</div>

<h2>Адвокаты, занятые в деле</h2>

<table class="table h4">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Lawyers.First().Surname)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Lawyers.First().Name)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Lawyers.First().Patronymic)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Case.Lawyers)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Patronymic)
            </td>
        </tr>
    }
</table>

<h2>Юридические процедуры по делу</h2>

<table class="table h4">
    <tr>
        <th class="text-center">
            <label>Дата оказания</label>
        </th>
        <th class="text-center">
            <label>Результат оказания</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.CaseLegalProcedures)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Result)
            </td>
        </tr>
    }

</table>
<p>
    @if (User.IsInRole("Administrator") || User.IsInRole("Lawyer"))
    {
        if (Model.Case.CaseStatusId == 1)
        {
            @Html.ActionLink("Редактировать информацию о деле", "Edit", new { id = Model.Case.Id })
        }
    }
</p>

LawOffice/LawOffice/Views/Cases/Edit.cshtml
@model LawOffice.Models.Case

@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать данные дела</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Number)
    @Html.HiddenFor(model => model.ClientId)
    @Html.HiddenFor(model => model.OpeningDate)

    <div class="form-horizontal h4">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="padding-top: 7px">
                @Html.DisplayFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpeningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="padding-top: 7px">
                @Html.DisplayFor(model => model.OpeningDate)
                @Html.ValidationMessageFor(model => model.CaseResultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CaseResultId, "Результат", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CaseResultId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CaseResultId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить изменения" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@if (User.IsInRole("Administrator"))
{
    <p>
        @Html.ActionLink("Назначить дополнительного адвоката", "Add", "Lawyers", new { id = Model.Id }, null)
    </p>
}

<p>
    @Html.ActionLink("Добавить новую процедуру", "Create", "CaseLegalProcedures", new { id = Model.Id }, null)
</p>

@if (User.IsInRole("Administrator"))
{
    <div>
        @Html.ActionLink("Вернуться к списку дел", "Index")
    </div>
}
@if (User.IsInRole("Lawyer"))
{
    <div>
        @Html.ActionLink("Назад", "Details", new { id = Model.Id })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LawOffice/LawOffice/Views/Cases/Index.cshtml
@model IEnumerable<LawOffice.Models.Case>

@{
    ViewBag.Title = "Index";
}

<h2>Дела</h2>

<p>
    @Html.ActionLink("Загрузить свежие данные с сервера", "LoadFromAPI")
</p>
<table class="table">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.OpeningDate)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.ClosingDate)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.CaseStatus.Name)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.CaseResult.Name)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Costs)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.OpeningDate)
            </td>
            <td class="text-center">
                @if (item.CaseStatusId == 2)
                {
                    @Html.DisplayFor(modelItem => item.ClosingDate)
                }
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.CaseStatus.Name)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.CaseResult.Name)
            </td>
            <td class="text-center">
                @if (item.Costs > 0)
                {
                    @Html.DisplayFor(modelItem => item.Costs)
                }
            </td>
            <td class="text-center">
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Подробности", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>