LawOffice/LawOffice/Models/Lawyer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LawOffice.Models
{
    public class Lawyer
    {    
        public int Id { get; set; }
        
        [Required, DisplayName("Фамилия")]
        public string Surname { get; set; }
        
        [Required, DisplayName("Имя")]
        public string Name { get; set; }
        
        [DisplayName("Отчество (при наличии)")]
        public string Patronymic { get; set; }

        [NotMapped]
        public string FIO
        {
            get
            {
                return (Surname + " " + Name + " " + Patronymic);
            }
        }

        [Required, ScaffoldColumn(false), DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        
        [NotMapped, DisplayName("Стаж работы (лет)")]
        public string LengthOfService { 
            get
            {
                string length = ((DateTime.Now - StartDate).Days / 365).ToString();
                if (length == "0")
				{
                    return "менее года";
				}
				else
				{
                    return length;
				}
            } 
        }
        
        public byte[] Photo { get; set; }

        [Required, DisplayName("Адрес электронной почты"), DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        public int LawyerStatusId { get; set; }        
        public LawyerStatus LawyerStatus { get; set; }
        
        public ICollection<Case> Cases { get; set; }
        
        public Lawyer()
        {
            Cases = new List<Case>();
        }
    }
}

LawOffice/LawOffice/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Windows.Media;
using System.Xml;
using LawOffice.Models;
using LawOffice.Synchronisation;
using LawOffice.ViewModels;
using MailKit.Net.Smtp;
using Microsoft.Ajax.Utilities;
using MimeKit;
using OfficeOpenXml;

namespace LawOffice.Controllers
{
	[Authorize]
	public class CasesController : Controller
	{
		private LawOfficeDBContext db = new LawOfficeDBContext();

		// GET: Cases
		public ActionResult Index ()
		{
			if (User.IsInRole("Administrator"))
			{
				var cases = db.Cases.Include(C => C.CaseResult).Include(S => S.CaseStatus).Include(C => C.Client);
				return View(cases.ToList());
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		public ActionResult LoadFromAPI ()
		{
			HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://localhost:44334/api/Cases");
			request.Accept = "application/xml";
			WebResponse response = request.GetResponse();
			XmlDocument doc = new XmlDocument();
			doc.Load(response.GetResponseStream());
			XmlElement root = doc.DocumentElement;
			foreach (XmlElement caseNode in root)
			{
				int id = Convert.ToInt32(caseNode["Id"].InnerText);
				Case @case = db.Cases.Find(id);
				if (@case == null)
				{
					Case newCase = new Case()
					{
						Number = caseNode["Number"].InnerText,
						ClientId = int.Parse(caseNode["ClientId"].InnerText),
						OpeningDate = DateTime.Parse(caseNode["OpeningDate"].InnerText),
						ClosingDate = DateTime.Parse(caseNode["ClosingDate"].InnerText),
						CaseStatusId = int.Parse(caseNode["CaseStatusId"].InnerText),
						CaseResultId = int.Parse(caseNode["CaseResultId"].InnerText),
						Costs = int.Parse(caseNode["Costs"].InnerText),
					};
					db.Cases.Add(newCase);
				}
				else
				{
					@case.Number = caseNode["Number"].InnerText;
					@case.ClientId = int.Parse(caseNode["ClientId"].InnerText);
					@case.OpeningDate = DateTime.Parse(caseNode["OpeningDate"].InnerText);
					@case.ClosingDate = DateTime.Parse(caseNode["ClosingDate"].InnerText);
					@case.CaseStatusId = int.Parse(caseNode["CaseStatusId"].InnerText);
					@case.CaseResultId = int.Parse(caseNode["CaseResultId"].InnerText);
					@case.Costs = int.Parse(caseNode["Costs"].InnerText);
				}
			}
			SynchronisationFromAPI synchronisation = new SynchronisationFromAPI();
			synchronisation.LoadCaseLegalProceduresFromAPI();
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		// GET: Cases/Details/5
		public ActionResult Details (int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			CaseDetails caseDetails = new CaseDetails();
			caseDetails.Case = db.Cases.Include(c => c.Client).Include(l => l.Lawyers).Include(c => c.CaseResult).Include(c => c.CaseStatus).Where(c => c.Id == id).FirstOrDefault();
			caseDetails.Lawyers = caseDetails.Case.Lawyers;
			caseDetails.CaseLegalProcedures = db.CasesLegalProcedures.Where(p => p.CaseId == id).ToList();
			if (caseDetails.Case == null)
			{
				return HttpNotFound();
			}
			return View(caseDetails);
		}

		// GET: Cases/Create
		public ActionResult Create (int id)
		{
			if (User.IsInRole("Administrator"))
			{
				ViewBag.CaseResultId = new SelectList(db.CaseResults, "Id", "Name");
				ViewBag.CaseStatusId = new SelectList(db.CaseStatuses, "Id", "Name");
				ViewBag.ClientId = new SelectList(db.Clients, "Id", "Surname");
				ViewBag.LawyerId = new SelectList(db.Lawyers, "Id", "FIO");
				ViewData["Id"] = id;
				return View();
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// POST: Cases/Create
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create ([Bind(Include = "Id,Number,ClientId,OpeningDate,ClosingDate,CaseStatusId,CaseResultId,Costs")] Case @case, int LawyerId)
		{
			if (User.IsInRole("Administrator"))
			{

				@case.CaseStatusId = 1;
				@case.CaseResultId = 4;
				@case.OpeningDate = DateTime.Now;
				@case.ClosingDate = DateTime.Now;
				bool isContains = false;
				foreach (Case c in db.Cases)
				{
					if (c.Number == @case.Number)
					{
						isContains = true;
					}
				}
				if (isContains)
				{
					ModelState.AddModelError("Number", "Дело должен иметь уникальный номер");
				}
				if (ModelState.IsValid)
				{
					@case.Lawyers.Add(db.Lawyers.Where(l => l.Id == LawyerId).First());
					db.Cases.Add(@case);
					db.SaveChanges();
					return RedirectToAction("Details", "Clients", new { id = @case.ClientId });
				}

				ViewBag.CaseResultId = new SelectList(db.CaseResults, "Id", "Name", @case.CaseResultId);
				ViewBag.CaseStatusId = new SelectList(db.CaseStatuses, "Id", "Name", @case.CaseStatusId);
				ViewBag.ClientId = new SelectList(db.Clients, "Id", "Surname", @case.ClientId);
				ViewBag.LawyerId = new SelectList(db.Lawyers, "Id", "Surname");
				return View(@case);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: Cases/Edit/5
		public ActionResult Edit (int? id)
		{
			if (User.IsInRole("Administrator") || User.IsInRole("Lawyer"))
			{
				if (id == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				Case @case = db.Cases.Find(id);
				if (@case == null)
				{
					return HttpNotFound();
				}
				if (@case.CaseStatusId == 2)
				{
					return RedirectToAction("Index");
				}
				ViewBag.CaseResultId = new SelectList(db.CaseResults, "Id", "Name", @case.CaseResultId);
				ViewBag.CaseStatusId = new SelectList(db.CaseStatuses, "Id", "Name", @case.CaseStatusId);
				ViewBag.ClientId = new SelectList(db.Clients, "Id", "Surname", @case.ClientId);
				return View(@case);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}
		// POST: Cases/Edit/5
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit ([Bind(Include = "Id,Number,ClientId,OpeningDate,ClosingDate,CaseStatusId,CaseResultId,Costs")] Case @case)
		{
			if (User.IsInRole("Administrator") || User.IsInRole("Lawyer"))
			{
				if (@case.CaseResultId != 4)
				{
					@case.CaseStatusId = 2;
					@case.Costs = GetCaseCosts(@case.Id, @case.CaseResultId);
					@case.ClosingDate = DateTime.Now;
				}
				if (ModelState.IsValid)
				{
					db.Entry(@case).State = EntityState.Modified;
					db.SaveChanges();
					@case = db.Cases.Include(c => c.Client).Where(c => c.Id == @case.Id).First();
					SendEmail(@case);
					return RedirectToAction("Index");
				}
				ViewBag.CaseResultId = new SelectList(db.CaseResults, "Id", "Name", @case.CaseResultId);
				ViewBag.CaseStatusId = new SelectList(db.CaseStatuses, "Id", "Name", @case.CaseStatusId);
				ViewBag.ClientId = new SelectList(db.Clients, "Id", "Surname", @case.ClientId);
				return View(@case);
			}
			else
			{
				return new HttpStatusCodeResult(403);
			}
		}

		// GET: Cases/Delete/5
		//public ActionResult Delete (int? id)
		//{
		//	if (id == null)
		//	{
		//		return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		//	}
		//	Case @case = db.Cases.Find(id);
		//	if (@case == null)
		//	{
		//		return HttpNotFound();
		//	}
		//	return View(@case);
		//}

		// POST: Cases/Delete/5
		//[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		//public ActionResult DeleteConfirmed (int id)
		//{
		//	Case @case = db.Cases.Find(id);
		//	db.Cases.Remove(@case);
		//	db.SaveChanges();
		//	return RedirectToAction("Index");
		//}

		[Authorize(Roles = "Administrator")]
		public FileResult GetEarnings (int id)
		{
			if (id == 1)
			{
				ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
				string originalFilePath = Server.MapPath("~/Content/Reports/earnings.xlsx");
				FileInfo originalFileInfo = new FileInfo(originalFilePath);
				string resultFilePath = Server.MapPath("~/Content/Reports/report.xlsx");
				FileInfo resultFileInfo = new FileInfo(resultFilePath);
				using (ExcelPackage excelPackage = new ExcelPackage(originalFileInfo))
				{
					excelPackage.Workbook.Properties.Author = "Mark Chuvanov";
					excelPackage.Workbook.Properties.Title = "Доход";
					excelPackage.Workbook.Properties.Subject = "Заработок";
					excelPackage.Workbook.Properties.Created = DateTime.Now;
					ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets["Earnings"];
					int startLine = 2;
					var cases = db.Cases.ToList();
					int startYear = 2019;
					int endYear = DateTime.Now.Year;
					for (int i = startYear; i <= endYear; i++)
					{
						worksheet.Cells[startLine, 1].Value = i;
						int earnings = 0;
						foreach (var @case in cases)
						{
							if (@case.ClosingDate.Year == i)
							{
								earnings += @case.Costs;
							}
						}
						worksheet.Cells[startLine, 2].Value = earnings;
						startLine++;
					}
					excelPackage.SaveAs(resultFileInfo);
				}
				string fileType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
				string fileName = "Earnings.xlsx";
				return File(resultFilePath, fileType, fileName);
			}
			else
			{
				//Генерация PDF-отчета
				return null;
			}
		}

		[Authorize(Roles = "Administrator")]
		public FileResult GetCases (int id, DateTime startDate, DateTime endDate)
		{
			if (id == 1)
			{
				ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
				string originalFilePath = Server.MapPath("~/Content/Reports/cases.xlsx");
				FileInfo originalFileInfo = new FileInfo(originalFilePath);

LawOffice/LawOffice/Views/Lawyers/Add.cshtml
@model IEnumerable<LawOffice.Models.Lawyer>

@{
    ViewBag.Title = "Index";
}

<h2>Назначить дополнительного адвоката</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal h4">
    <hr />
    @Html.Hidden("CaseId", ViewData["Id"])
    <div class="form-group">
        <label class="control-label col-md-2">Адвокат</label>
        <div class="col-md-10">
            @Html.DropDownList("LawyerId", ViewBag.LawyerId as SelectList, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Назначить адвоката" class="btn btn-success" />
        </div>
    </div>
</div>
}

LawOffice/LawOffice/Views/Lawyers/Create.cshtml
@model LawOffice.Models.Lawyer

@{
    ViewBag.Title = "Create";
}

<h2>Добавить нового адвоката</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Добавить адвоката" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку адвокатов", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LawOffice/LawOffice/Views/Lawyers/Details.cshtml
@model LawOffice.ViewModels.LawyerDetails

@{
    ViewBag.Title = "Details";
}

<h2>Подробная информация об адвокате</h2>

<div>
    <hr />
    <dl class="dl-horizontal h4">

        <dt style="width: 250px; margin-right:10px">
            @Html.DisplayNameFor(model => model.Lawyer.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lawyer.Surname)
        </dd>

        <dt style="width: 250px; margin-right:10px">
            @Html.DisplayNameFor(model => model.Lawyer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lawyer.Name)
        </dd>

        <dt style="width: 250px; margin-right:10px">
            @Html.DisplayNameFor(model => model.Lawyer.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lawyer.Patronymic)
        </dd>

        <dt style="width: 250px; margin-right:10px">
            @Html.DisplayNameFor(model => model.Lawyer.LengthOfService)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lawyer.LengthOfService)
        </dd>

        <dt style="width: 250px; margin-right:10px">
            @Html.DisplayNameFor(model => model.Lawyer.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lawyer.Email)
        </dd>

    </dl>
</div>

<h2>Дела</h2>

<table class="table h4">
    <tr>
        <th class="text-center">
            <label>Номер</label>
        </th>
        <th class="text-center">
            <label>Дата открытия</label>
        </th>
        <th class="text-center">
            <label>Дата закрытия</label>
        </th>
        <th class="text-center">
            <label>Статус</label>
        </th>
        <th class="text-center">
            <label>Результат</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Cases)
    {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.OpeningDate)
            </td>
            <td class="text-center">
                @if (item.CaseStatusId == 2)
                {
                    @Html.DisplayFor(modelItem => item.ClosingDate)
                }
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.CaseStatus.Name)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.CaseResult.Name)
            </td>
            <td class="text-center">
                @Html.ActionLink("Подробности", "Details", "Cases", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>
@if (User.IsInRole("Administrator"))
{
    <p>
        @Html.ActionLink("Редактировать данные", "Edit", new { id = Model.Lawyer.Id }) |
        @Html.ActionLink("Вернуться к списку адвокатов", "Index")
    </p>
}

LawOffice/LawOffice/Views/Lawyers/Edit.cshtml
@model LawOffice.Models.Lawyer

@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать персональные данные адвоката</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div>
            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <!--<div>-->
            @*Добавить изображение*@
            <!--<img src="~/Controllers/LawyersController/"/>
        </div>-->

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, "Дата начала работы", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9" style="padding-top: 7px">
                @Html.DisplayFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LawyerStatus.Name, "Статус", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownList("LawyerStatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LawyerStatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Сохранить изменения" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку адвокатов", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LawOffice/LawOffice/Views/Lawyers/Index.cshtml
@model IEnumerable<LawOffice.Models.Lawyer>

@{
    ViewBag.Title = "Index";
}

<h2>Адвокаты</h2>

<p>
    @Html.ActionLink("Загрузить свежие данные с сервера", "LoadFromAPI")
</p>
<p>
    @Html.ActionLink("Добавить нового адвоката", "Create")
</p>
<table class="table h4">
    <tr>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.Patronymic)
        </th>
        <th class="text-center">
            @Html.DisplayNameFor(model => model.LengthOfService)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        if (item.LawyerStatus.Name == "Работает")
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Patronymic)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.LengthOfService)
                </td>
                <td class="text-center">
                    @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Подробности", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    }
</table>